### ISSUE TITLE
Creating users or databases doesn't work

### ISSUE THREAD

**Issue by akheron** [akumria/puppet-postgresql#17]
My config is as follows:

```
class {'postgresql': }
class {'postgresql::server':
  listen => ['localhost'],
}
pg_user { 'foo':
  ensure   => present,
  password => 'foo',
}
pg_database { 'foo':
  ensure  => present,
  owner   => 'foo',
  require => Pg_user['foo'],
}
```

The postgresql server and client are installed as expected, but the user and database are not created. I'm unsure how to debug this.

**Comment by akumria** [comment]
Do you have pluginsync enabled?

Anand

On 3 October 2012 12:40, Petri Lehtinen notifications@github.com wrote:

> My config is as follows:
> 
> class {'postgresql': }
> class {'postgresql::server':
>   listen => ['localhost'],
> }
> pg_user { 'foo':
>   ensure   => present,
>   password => 'foo',
> }
> pg_database { 'foo':
>   ensure  => present,
>   owner   => 'foo',
>   require => Pg_user['foo'],
> }
> 
> The postgresql server and client are installed as expected, but the user
> and database are not created. I'm unsure how to debug this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/akumria/puppet-postgresql/issues/17.

## 

“Don’t be sad because it’s over. Smile because it happened.” – Dr. Seuss

**Comment by akheron** [comment]
Ah, no I didn't. After enabling pluginsync, it works perfectly. Sorry for the noise.
