### ISSUE TITLE
Puppet module contains Vim Swap files

### ISSUE THREAD

**Issue by dol** [akumria/puppet-postgresql#18]
The Puppet module on http://forge.puppetlabs.com/akumria/postgresql/1.1.0.tar.gz contains the following Vim swap files:
- ./manifests/.db.pp.swp
- ./manifests/.server.pp.swp
- ./lib/puppet/type/.pg_database.rb.swp
- ./lib/puppet/provider/pg_database/.debian_postgresql.rb.swp

**Comment by akumria** [comment]
Thanks for letting me know.

I've just released an update, and tweaked my processes so this should not happen again.
