### ISSUE TITLE
Unknown id: postgres

### ISSUE THREAD

**Issue by philsturgeon** [akumria/puppet-postgresql#2]
Here is a screenshot of my error: http://d.pr/i/KeWs

```
err: /Stage[main]//Pg_user[pyrocms]: Could not evaluate: Execution of '/bin/su - postgres -c psql --quiet -A -t -c "select 1 from pg_roles where rolname = 'pyrocms';"' returned 1: Unknown id: postgres

notice: /Stage[main]//Pg_database[pyrocms]: Dependency Pg_user[pyrocms] has failures: true
warning: /Stage[main]//Pg_database[pyrocms]: Skipping because of failed dependencies
notice: Finished catalog run in 0.51 seconds
```

Any ideas whats up here?

**Comment by akumria** [comment]
For some reason, the user 'postgres' was not created when the postgresql packages were installed.

Were they properly installed?

**Comment by philsturgeon** [comment]
It's got the binaries down, not sure what else needs to be done?

```
ls /usr/lib/postgresql/9.1/bin/ 
clusterdb  createdb  createlang  createuser  dropdb  droplang  dropuser  pg_basebackup  pg_dump  pg_dumpall  pg_restore  psql  reindexdb  vacuumdb
```

**Comment by akumria** [comment]
Does the user 'postgres' exist?

If not, why not? The Debian (and Ubuntu) packages create that user on
installation.

You need to determine why that user was not created when the package
was installed.

On 19 July 2012 02:12, Phil Sturgeon
reply@reply.github.com
wrote:

> It's got the binaries down, not sure what else needs to be done?
> 
> ```
> ls /usr/lib/postgresql/9.1/bin/
> clusterdb  createdb  createlang  createuser  dropdb  droplang  dropuser  pg_basebackup  pg_dump  pg_dumpall  pg_restore  psql  reindexdb  vacuumdb
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/akumria/puppet-postgresql/issues/2#issuecomment-7087312

## 

“Don’t be sad because it’s over. Smile because it happened.” – Dr. Seuss

**Comment by philsturgeon** [comment]
Adding `class {'postgresql::server': }` fixed it. My bad.
