### ISSUE TITLE
module version error at puppetlabs?

### ISSUE THREAD

**Issue by imbunche** [akumria/puppet-postgresql#20]
I installed your module  from puppetlabs and it is advertised as (v1.1.1)
$ puppet install module akumria-postgresql

However your git repo claims v1.1.1 implementes the $preacl features which you do not get from the puppetlabs downloaded version.

Can you fix this misalignment?

**Comment by akumria** [comment]
Hi,

There is no 'misalignment'.

If you look at https://github.com/akumria/puppet-postgresql/commits/master you will see commit 66056b7da50886faba493670449436126243e8a3.

If you look at https://github.com/akumria/puppet-postgresql/tags you will see commit 66056b is tag v1.1.1

Which is exactly what was upload to the puppetforge.

The git repository has _additional_ commits which have not been put into a release (as yet).

I've now tagged v1.2.0 which includes those commits.
