### ISSUE TITLE
pg_user need require package['postgres']

### ISSUE THREAD

**Issue by SaitoWu** [akumria/puppet-postgresql#3]
``` puppet
# postgresql
class { 'postgresql::server':
  version => '9.1',
}
pg_user { $postgresql['user']:
  ensure   => present,
  password => $postgresql['password'],
  createdb   => true,
  createrole => true
}
```

error:

``` bash
err: /Stage[main]//Pg_user[root]: Could not evaluate: Execution of '/bin/su - postgres -c psql --quiet -A -t -c "select 1 from pg_roles where rolname = 'root';"' returned 1: Unknown id: postgres
```

When i first execute the puppet script. I got this error message.

And the second gonna be ok.

So, must ensure `pg_user` is after `postgres::server` installed.

Maybe should  add `require => package['postgres']` to fix it.

**Comment by akumria** [comment]
I'm not sure where I should add that.

Can I put this into the type?

If I put it into postgresql::db, it ties things to a specific version.

Suggestions?

**Comment by SaitoWu** [comment]
I've no idea in the source code.

But when i use this recipe, i think the best way is:

``` puppet
# postgresql
class { 'postgresql::server':
  version => '9.1',
}
pg_user { $postgresql['user']:
  ensure   => present,
  password => $postgresql['password'],
  createdb   => true,
  createrole => true,
  require => package['postgres']
}
```

**Comment by akumria** [comment]
Sure, but that recipe is done by you. 

I'll update the documentation to recommend a dependency.

Note that their is no package called 'postgres'. The 'postgresql' package is a meta package, and it assumes you always want the latest version of postgresql installed.

I've not made that assumption, I allow you to install older version of postgres, if required.

**Comment by SaitoWu** [comment]
cool!. make sence. :beers:
