### ISSUE TITLE
Allow template to be specified when creating a database

### ISSUE THREAD

**Issue by codeinthehole** [akumria/puppet-postgresql#8]
At the moment, the template is hard-coded to be template0:
https://github.com/akumria/puppet-postgresql/blob/master/lib/puppet/provider/pg_database/debian_postgresql.rb#L11

Could this be altered so that an alternative template can be passed?

**Comment by akumria** [comment]
The code is in and documented but I've not had a chance to thoroughly test it myself, which is why it is not in a release.

If you are able to confirm that this works for you, I can roll another release later today.

**Comment by codeinthehole** [comment]
Yes, that worked fine for me.  Thanks!
